In [6]:
import random

# generate sudo random numbers (seems random but can be reproducible)
a = random.random()
print(a)
#start and stop
a = random.uniform(1, 5)
print(a)
# int from start and stop (end included)
a = random.randint(1, 15)
print(a)
# int from start and stop (end exluded)
a = random.randrange(1, 15)
print(a)

0.5611869495030746
4.723356860518483
9
12


In [7]:
# pick a random of mean 0 and SD 1
a = random.normalvariate(0, 1)
print(a)

0.8446009378824543


In [9]:
# choose one element from a list
my_list = list("ASHGGHFJGHKJ")
c = random.choice(my_list)
print(c)

K


In [12]:
# choose unique elements from a list
my_list = list("ASHGGHFJGHKJ")
c = random.sample(my_list, 3)
print(c)

['K', 'H', 'G']


In [22]:
# choose elements from a list (not unique)
my_list = list("ASHGGHFJGHKJ")
#k= #of choices
c = random.choices(my_list, k=3)
print(c)
#and you can even assign weights
c = random.choices(my_list, k=3, weights=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(c)


['H', 'S', 'K']
['J', 'F', 'K']


In [25]:
# shuffle list in place
random.shuffle(my_list)
print(my_list)

['G', 'H', 'J', 'G', 'H', 'A', 'J', 'G', 'K', 'H', 'F', 'S']


In [27]:
# you can set a seed to make the random number always appear
random.seed(1)
print(random.random())
random.seed(1)
print(random.random())

0.13436424411240122
0.13436424411240122


In [30]:
# since it's not safe to use random for security purpose,
# we can't use it simply for secure programs, so we use secrets
import secrets
# Disadvantage of it that it takes more time, but it generates a true random number
# Exclusive upper bound
a = secrets.randbelow(10)
print(a)
# Return int with K binary bits
# 3 bits make the upper bound 15
a = secrets.randbits(4)
print(a)
# Chooses randomly from a list
a = secrets.choice(my_list)
print(a)

2
5
G


In [37]:
# use numpy to create a true random arrays
import numpy as np
# 3,3 are dimensions
a = np.random.rand(3,3)
print(a)
# range (upper is excluded)
# 0,10 are bounds, 3 is for the count of numbers
a = np.random.randint(0,10, 3)
# shuffle shuffles only the first axis
np.random.shuffle(a)
print(a)

# seed
np.random.seed(1)

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]
[4 2 5]
